### ISSUE TITLE
Add ability to pass a login hint in the url

### ISSUE THREAD

**Issue by stevehansen** [Vidyano/vidyano#23]
We need a way to pass a username in the initial url that should be used on the sign in page.

This would allow for linking to an application where we already know the username (i.e. because we are switching from an existing application).

Ideally this would trigger the sign in flow as if the user typed in their own user name so that if GetCredentialType tries to redirect that this would happen immediately, to handle SSO scenarios.

**Comment by Sleeckx** [comment]
Added in 38547f918668c7758cf2a7898a426274dec3f0c7
