### ISSUE TITLE
Attribute label does not refresh

### ISSUE THREAD

**Issue by ThierryRosseau** [Vidyano/vidyano#31]
We have the following senario:

On a PO we have a custom action that opens a dialog PO. When saving that dialog PO we modify the enity and call RefreshOperation. In de OnLoad from the refreshing PO we modify the label. This modification does not show in the interface. Netwerk result shows correct label is send.

Expertise PO
- Custom Action 'Override Contact'
 - Open OverrideContactDialog PO (AsDialog)
   - OnSave update entity and call RefreshOperation(obj.Parent) (Refresh Expertise)
     - OnLoad on Expertise PO we modify label
      - Modification is not shown 

After F5 the label is shown correctly

![Screenshot 2024-02-23 at 13 22 39](https://github.com/Vidyano/vidyano/assets/50580460/0f2568e0-e388-4fee-8ec3-51eb02bd8467)
![Screenshot 2024-02-23 at 13 23 08](https://github.com/Vidyano/vidyano/assets/50580460/7ce24a0f-b61e-4a7c-85cc-e1695cd8d53d)

**Comment by Sleeckx** [comment]
Fixed in #36
